name: qubo-receptor-ensemble
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - matplotlib
  - dimod=0.12.22
  - dwave-samplers=1.7.0
  - dwave-system=1.24.0
  - meeko=0.7.1
  - numpy
  - pandas
  - prody=2.4.1
  - pytest
  - rdkit=2026.03.1
  - scikit-learn
  - scipy
  - seaborn
  - setuptools<81
  - xgboost=3.1.1
  - pip
  - pip:
      - -e ..
